### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by LeiserGeist** [OpenPrograms/Gopher-Programs#7]
Probably a bad title.
I tried a bunch of things to make a constantly-updating display (update displayed information every x) but it doesn't seem possible with the way things are done.
I tried adding a call in the main while loop but it pauses to wait for events, so that idea's out.

Am I completely looking past something? Or is there anything you can think of?

**Comment by Gopher42** [comment]
sorry for the slow response; dunno if you're still working on this program even, much less this specific issue, but you would use a timer handled by your main loop to update the values of the fields, and you should be able to just call the :draw() method on each field you update the value of, since they aren't data-aware and won't re-draw automatically.

**Comment by LeiserGeist** [comment]
I jammed in a little workaround -  a 0.1 second timeout on the event pull. Not really a good solution, but it worked for what I needed.
Next time I do something like this I'll be sure to try your way! Thank you.
